### ISSUE TITLE
Figure not found in App.tsx

### ISSUE THREAD

**Issue by Losses** [microsoft/create-react-app-uifabric#1]
[This file](https://raw.githubusercontent.com/Microsoft/just/master/packages/just-stack-uifabric/template/src/components/fabric.png
) is not found.

Which cause:
![image](https://user-images.githubusercontent.com/1384036/63644689-537c1600-c721-11e9-87f7-ff44262ce750.png)

**Comment by BhanuKorthiwada** [comment]
This is fixed in #2

**Comment by Losses** [comment]
Oh, Cool!
